-- SQL dump generated using DBML (dbml-lang.org)
-- Database: PostgreSQL
-- Generated at: 2023-10-21T06:25:35.628Z

CREATE TABLE "Sales" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "StockNumber" varchar(255) NOT NULL,
  "VehicleMake" varchar(255) NOT NULL,
  "ActualCashValue" decimal(10,2) NOT NULL,
  "GrossProfit" decimal(10,2) NOT NULL,
  "FinAndInsurance" decimal(10,2) NOT NULL,
  "SaleTime" timestamp DEFAULT (now()),
  "NewSale" boolean,
  "Holdback" decimal(10,2),
  "LotPack" decimal(10,2),
  "DaysInStock" int,
  "DealerCost" decimal(10,2),
  "ROI" decimal(3,2),
  "EmployeeID" int NOT NULL,
  "CustomerID" int NOT NULL,
  "FinancingID" int,
  "TradeInID" int
);

CREATE TABLE "MonthlySales" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "TimePeriod" timestamp NOT NULL,
  "GrossProfit" decimal(10,2) NOT NULL,
  "FinAndInsurance" decimal(10,2) NOT NULL,
  "Holdback" decimal(10,2) NOT NULL,
  "Total" decimal(10,2) NOT NULL
);

CREATE TABLE "Roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "RoleName" varchar(255),
  "ReadPermission" boolean NOT NULL DEFAULT false,
  "WritePermission" boolean NOT NULL DEFAULT false,
  "ModifySelfPermission" boolean NOT NULL DEFAULT false,
  "ModifyAllPermission" boolean NOT NULL DEFAULT false,
  "EmployeePermission" boolean NOT NULL DEFAULT false,
  "DatabasePermission" boolean NOT NULL DEFAULT false
);

CREATE TABLE "Employees" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "Name" varchar(255) NOT NULL,
  "EmployeeNumber" varchar(255) NOT NULL,
  "Email" TEXT NOT NULL,
  "Password" TEXT NOT NULL,
  "Role" int NOT NULL,
  "CreatedOn" timestamp NOT NULL DEFAULT (now()),
  "LastAccessed" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "Customers" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "Name" varchar(255) NOT NULL,
  "City" varchar(255) NOT NULL
);

CREATE TABLE "Financing" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "Method" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE "TradeIns" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "Trade" varchar(255) NOT NULL,
  "ActualCashValue" decimal(10,2) NOT NULL
);

CREATE TABLE "Tasks" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "Name" varchar(255) NOT NULL,
  "Description" TEXT,
  "PercentageComplete" decimal(3,2),
  "StartDate" timestamp NOT NULL DEFAULT (now()),
  "EndDate" timestamp NOT NULL DEFAULT (now()),
  "Assignee" int,
  "Creator" int
);

CREATE TABLE "SalesGoals" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "Name" varchar(255) NOT NULL,
  "Description" TEXT,
  "Creator" int NOT NULL,
  "StartDate" timestamp NOT NULL DEFAULT (now()),
  "EndDate" timestamp NOT NULL DEFAULT (now()),
  "TotalGoal" decimal(10,2) NOT NULL
);

CREATE TABLE "Notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "Employee" int NOT NULL,
  "Sale" int NOT NULL
);

COMMENT ON COLUMN "Sales"."NewSale" IS 'set based on New/Used sale';

COMMENT ON COLUMN "Sales"."Holdback" IS 'new sale only';

COMMENT ON COLUMN "Sales"."LotPack" IS 'used sale only';

COMMENT ON COLUMN "Sales"."DaysInStock" IS 'used sale only';

COMMENT ON COLUMN "Sales"."DealerCost" IS 'used sale only';

COMMENT ON COLUMN "Sales"."ROI" IS 'used sale, percentage as decimal.';

COMMENT ON COLUMN "MonthlySales"."TimePeriod" IS 'Timestamp in the form of YYYY-MM-01 00:00:00';

COMMENT ON COLUMN "Roles"."ReadPermission" IS 'Allow user to read created sales';

COMMENT ON COLUMN "Roles"."WritePermission" IS 'Allow user to create new sales';

COMMENT ON COLUMN "Roles"."ModifySelfPermission" IS 'Allow user to modify previously entered sales that were created by that user.';

COMMENT ON COLUMN "Roles"."ModifyAllPermission" IS 'Allow user to modify previously entered sales that were created by anyone.';

COMMENT ON COLUMN "Roles"."EmployeePermission" IS 'Allow user to manage employees (create, remove, etc..)';

COMMENT ON COLUMN "Roles"."DatabasePermission" IS 'Allow user to modify database directly (drop tables etc...). Highest privilege.';

COMMENT ON COLUMN "Employees"."Email" IS 'max len(320)';

COMMENT ON COLUMN "Employees"."Password" IS 'salted hash of a password';

COMMENT ON COLUMN "Employees"."CreatedOn" IS 'Extra optional metadata for `admin` type roles to access';

COMMENT ON COLUMN "Employees"."LastAccessed" IS 'Extra optional metadata for `admin` type roles to access';

COMMENT ON COLUMN "TradeIns"."Trade" IS 'Name of a car that was traded-in';

ALTER TABLE "Sales" ADD FOREIGN KEY ("EmployeeID") REFERENCES "Employees" ("id");

ALTER TABLE "Sales" ADD FOREIGN KEY ("CustomerID") REFERENCES "Customers" ("id");

ALTER TABLE "Sales" ADD FOREIGN KEY ("FinancingID") REFERENCES "Financing" ("id");

ALTER TABLE "Sales" ADD FOREIGN KEY ("TradeInID") REFERENCES "TradeIns" ("id");

ALTER TABLE "Employees" ADD FOREIGN KEY ("Role") REFERENCES "Roles" ("id");

ALTER TABLE "Tasks" ADD FOREIGN KEY ("Assignee") REFERENCES "Employees" ("id");

ALTER TABLE "Tasks" ADD FOREIGN KEY ("Creator") REFERENCES "Employees" ("id");

ALTER TABLE "SalesGoals" ADD FOREIGN KEY ("Creator") REFERENCES "Employees" ("id");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("Employee") REFERENCES "Employees" ("id");

ALTER TABLE "Notifications" ADD FOREIGN KEY ("Sale") REFERENCES "Sales" ("id");
