

###
# @name Get all tasks
GET http://localhost:3000/api/task
Cookie: {{cookie}}

###
# @name Get a single task
GET http://localhost:3000/api/task/1
Cookie: {{cookie}}
###
# @name Create a single task
POST http://localhost:3000/api/task
Content-Type: application/json
Cookie: {{cookie}}

{
  "Name": "CREATE_TEST",
  "Creator": "1cf7cec8-74a0-4bb6-8364-b03f9a02b33a",
  "Assignee": "1cf7cec8-74a0-4bb6-8364-b03f9a02b33a"
}
