create table
  public."Customers" (
    id integer generated by default as identity,
    "Name" character varying(255) not null,
    "City" character varying(255) not null,
    constraint Customers_pkey primary key (id)
  ) tablespace pg_default;


create table
  public."Roles" (
    id integer generated by default as identity,
    "RoleName" character varying(255) null,
    "ReadPermission" boolean not null default false,
    "WritePermission" boolean not null default false,
    "ModifySelfPermission" boolean not null default false,
    "ModifyAllPermission" boolean not null default false,
    "EmployeePermission" boolean not null default false,
    "DatabasePermission" boolean not null default false,
    constraint Roles_pkey primary key (id),
    constraint Roles_RoleName_key unique ("RoleName")
  ) tablespace pg_default;

create table
  public."Employees" (
    id uuid not null,
    "Name" text not null,
    "EmployeeNumber" text not null,
    "Role" integer not null,
    "Email" text not null,
    "Avatar" text not null default '01.png'::text,
    constraint employees_pkey primary key (id),
    constraint employees_role_fkey foreign key ("Role") references "Roles" (id) on update cascade,
    constraint employees_id_fkey foreign key (id) references auth.users (id) on delete cascade
  ) tablespace pg_default;

create table
  public."Financing" (
    id integer generated by default as identity,
    "Method" character varying(255) not null,
    constraint Financing_pkey primary key (id),
    constraint Financing_Method_key unique ("Method")
  ) tablespace pg_default;

create table
  public."MonthlySales" (
    id integer generated by default as identity,
    "TimePeriod" timestamp without time zone not null,
    "GrossProfit" numeric(10, 2) not null,
    "FinAndInsurance" numeric(10, 2) not null,
    "Holdback" numeric(10, 2) not null,
    "Total" numeric(10, 2) not null,
    constraint MonthlySales_pkey primary key (id)
  ) tablespace pg_default;

create table
  public."TradeIns" (
    id integer generated by default as identity,
    "Trade" character varying(255) not null,
    "ActualCashValue" numeric(10, 2) not null,
    constraint TradeIns_pkey primary key (id)
  ) tablespace pg_default;

create table
  public."Sales" (
    id integer generated by default as identity,
    "StockNumber" character varying(255) not null,
    "VehicleMake" character varying(255) not null,
    "ActualCashValue" numeric(10, 2) not null,
    "GrossProfit" numeric(10, 2) not null,
    "FinAndInsurance" numeric(10, 2) not null,
    "SaleTime" timestamp without time zone null default now(),
    "NewSale" boolean null,
    "Holdback" numeric(10, 2) null,
    "LotPack" numeric(10, 2) null,
    "DaysInStock" integer null,
    "DealerCost" numeric(10, 2) null,
    "ROI" numeric(3, 2) null,
    "Total" numeric(10, 2) not null,
    "CustomerID" integer not null,
    "FinancingID" integer null,
    "TradeInID" integer null,
    "EmployeeID" uuid not null,
    constraint Sales_pkey primary key (id),
    constraint Sales_CustomerID_fkey foreign key ("CustomerID") references "Customers" (id),
    constraint Sales_EmployeeID_fkey foreign key ("EmployeeID") references "Employees" (id) on update cascade,
    constraint Sales_FinancingID_fkey foreign key ("FinancingID") references "Financing" (id),
    constraint Sales_TradeInID_fkey foreign key ("TradeInID") references "TradeIns" (id)
  ) tablespace pg_default;

create table
  public."Notifications" (
    id bigint generated by default as identity,
    "Sale" integer not null,
    "Employee" uuid not null,
    constraint Notifications_pkey primary key (id),
    constraint Notifications_Employee_fkey foreign key ("Employee") references "Employees" (id) on update cascade on delete cascade,
    constraint Notifications_Sale_fkey foreign key ("Sale") references "Sales" (id)
  ) tablespace pg_default;




create table
  public."SalesGoals" (
    id integer generated by default as identity,
    "Name" character varying(255) not null,
    "Description" text null,
    "StartDate" timestamp without time zone not null default now(),
    "EndDate" timestamp without time zone not null default now(),
    "TotalGoal" numeric(10, 2) not null,
    "Creator" uuid not null,
    constraint SalesGoals_pkey primary key (id),
    constraint SalesGoals_Creator_fkey foreign key ("Creator") references "Employees" (id)
  ) tablespace pg_default;

create table
  public."Tasks" (
    id integer generated by default as identity,
    "Name" character varying(255) not null,
    "Description" text null,
    "PercentageComplete" numeric(3, 2) null,
    "StartDate" timestamp without time zone not null default now(),
    "EndDate" timestamp without time zone not null default now(),
    "Assignee" uuid null,
    "Creator" uuid not null,
    constraint Tasks_pkey primary key (id),
    constraint Tasks_Assignee_fkey foreign key ("Assignee") references "Employees" (id) on update cascade on delete cascade,
    constraint Tasks_Creator_fkey foreign key ("Creator") references "Employees" (id) on update cascade on delete cascade
  ) tablespace pg_default;
